source 'http://rubygems.org'
gem 'rails', '3.1.0'

gem 'log4r'
gem 'mongoid'
gem 'bson_ext'
gem 'redis', :git=> 'git://github.com/ezmobius/redis-rb.git'

gem 'bcrypt-ruby'

gem 'sunspot_rails'
gem 'sunspot_mongoid'
gem 'vinova_sunspot_mongoid', :require => 'sunspot_mongoid'
gem 'rake','0.8.7'
gem 'mongoid_rails_migrations', '>=0.0.2' 
gem 'rails3-generators'

gem 'resque'
gem 'resque-scheduler'

gem 'daemon-spawn-tanin'

gem 'whowish_word', '0.2.0'
gem 'ruby_redis_lock'

group :development do
	gem 'capistrano'
end

group :test do
	gem 'resque_spec'
	
	gem 'rspec'
	gem 'rspec-rails'
	gem 'database_cleaner'
	gem 'factory_girl', '>=2.0'
	gem 'factory_girl_rails'
	gem 'mongoid-rspec'
	
	gem 'watir-webdriver-rails'
	
	gem 'win32-process', :platforms=>:mingw
	gem 'spork', :git => "git://github.com/timcharper/spork.git"
end

group :development, :test do
	gem 'linecache19', '0.5.11'
	gem 'ruby-debug19'
end


