log4r_config:
  # define all loggers ...
  loggers:
    - name      : production
      level     : WARN
      trace     : 'true'
      outputters :
      - datefile
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile
      - normal
    - name      : staging
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile
      - normal
    - name      : test
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile
      - normal

  # define all outputters (incl. formatters)      
  outputters:
    - type     : StderrOutputter
      name     : normal 
      level    : DEBUG
      formatter:
        date_pattern: '%y%m%d %H:%M:%S'
        pattern     : "[%l] %d :: %m"
        type        : PatternFormatter

    - type        : DateFileOutputter
      name        : datefile
      level       : DEBUG
      date_pattern: '%Y%m%d'
      trunc       : 'false'
      dirname     : "#{RAILS_ROOT}/log"
      formatter   :
        date_pattern: '%y%m%d %H:%M:%S'
        pattern     : "[%l] %d :: %m"
        type        : PatternFormatter

